version: '3.7'
services:
  otus_service:
    image: otus-ms-architecture:latest
    container_name: otus-ms-architecture
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8001:8000"
    env_file:
      - .env