---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: otus
data:
#  DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres/postgres
  GREETING: Bonjour
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: otus
type: Opaque
data:
  DATABASE_URI: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzL3Bvc3RncmVz