apiVersion: batch/v1
kind: Job
metadata:
  name: "otus-app-migration"
spec:
  template:
    metadata:
      name: "otus-app-migration"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              psql postgres://postgres:postgres@otus-app-postgresql:5432/postgres <<'EOF'
              create table "user"
              (
                  id          serial
                      primary key,
                  username    varchar(128) not null
                      unique,
                  "firstName" varchar(128),
                  "lastName"  varchar(128),
                  email       varchar(128),
                  phone       varchar(12)
              );
              
              alter table "user"
                  owner to postgres;
              
              create index ix_user_id
                  on "user" (id);
              EOF
  backoffLimit: 0