apiVersion: v2
name: app-chart
description: A Helm chart for Kubernetes

type: application

version: 0.3.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: "8.9.4"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - otus-app-database
